receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: "0.0.0.0:4317"
      http:




exporters:
  prometheus:
    endpoint: "0.0.0.0:9001"



  otlp:
    endpoint: "tempo:4317" 
    tls:
      insecure: true


processors:
  batch:
    send_batch_size: 1024
    timeout: 5s



service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
