auth_enabled: false

server:
  http_listen_port: 9000
  log_level: info
  log_format: json
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s
  http_server_idle_timeout: 2m

common:
  path_prefix: /var/lib/loki #as in compose
  instance_addr: 127.0.0.1
  replication_factor: 1

  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules

  ring:
    kvstore:
      store: inmemory

 


limits_config: 
  max_cache_freshness_per_query: 10m
  max_streams_per_user: 50000
  max_global_streams_per_user: 200000
  max_entries_limit_per_query: 10000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_series: 5000
  max_query_parallelism: 12
  max_concurrent_tail_requests: 20
  allow_structured_metadata: true


schema_config:
  configs:
    - from: 2025-01-01           
      store: tsdb                 
      object_store: filesystem #obviously, must be s3 in prod
      schema: v13                 
      index:
        prefix: index_           
        period: 24h 


compactor: 
  working_directory: /var/lib/loki/compactor
  retention_enabled: true
  retention_delete_delay: 1h
  delete_request_store: filesystem

ingester:
  wal:
    enabled: true
    dir: /var/lib/loki/wal
  chunk_idle_period: 15m
  chunk_retain_period: 30s
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1


query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true


ruler:
  storage:
    type: local
    local:
      directory: /var/lib/loki/rules
  rule_path: /var/lib/loki/rules-temp
  enable_api: true                     
  poll_interval: 1m
  evaluation_interval: 1m
  alertmanager_url: http://alertmanager:9000


#planning on using tempo further
tracing:
  enabled: false

